### ISSUE TITLE
Is this compatible with Activerecord's multiple databases support?

### ISSUE THREAD

**Issue by tenshiAMD** [rails-on-services/apartment#148]
Greetings to the maintainers.

Is this compatible with Activerecord's multiple databases support? (https://guides.rubyonrails.org/active_record_multiple_databases.html)

**Comment by rpbaltazar** [comment]
We are using in production a reader and a writer with apartment and have not yet faced major issues.
We did write our database selector logic do decide whether to connect to the reader or the writer because our API has some get requests that create records.

The default activerecord db selector does the switch based on (something along these lines).

is it a GET request ? If yes, has there been a recent write? If yes then go to the writer db else go to the reader.

Our logic includes an allow list/deny list of api endpoints that we apply on top of the existing GET logic. so even if its a GET request but its on the deny list, it will always go to the writer.
Furthermore, we have a redis key for the recent write logic so we can separate the tenants. A recent write on Tenant 1 should not have influence on the Tenant 2 requests.

Generically that's what we have configured.

**Comment by rpbaltazar** [comment]
Something along these lines for our database yml

```yaml
default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch('DATABASE_POOL_SIZE') { 5 } %>
  variables:
    statement_timeout: <%= ENV.fetch('STATEMENT_TIMEOUT') { '10s' } %>
  postgis_schema: postgis
  schema_search_path: 'public,postgis'

localtest: &localtest
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'db') %>
  username: <%= ENV.fetch('DATABASE_USER', 'user') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'password') %>

development:
  primary:
    <<: *localtest
    port: 5432
    database: platform_development
    gssencmode: disable

  primary_replica:
    <<: *localtest
    port: 5433
    database: platform_development
    gssencmode: disable
    replica: true

test:
  primary:
    <<: *localtest
    port: 5432
    database: platform_test
    gssencmode: disable

  primary_replica:
    <<: *localtest
    port: 5432
    database: platform_test
    gssencmode: disable
    replica: true

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_READER_URL'] %>
    replica: true
```
