### ISSUE TITLE
Apartment gem does not honor custom port for replica in Rails 6 multi-database setup

### ISSUE THREAD

**Issue by henriquekraemer** [rails-on-services/apartment#318]
When using Rails 6 multi-database support with the Apartment gem, if you define a replica connection (`primary_replica`) on a different port than the primary in `config/database.yml`, Apartment attempts to connect to the replica using the default PostgreSQL port (5432) instead of the custom port specified (e.g., 5433).

Example `config/database.yml`
```yaml
default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: postgres
  pool: 5

development:
  primary:
    <<: *default
    database: suite_development
    host: db
    port: 5432
  primary_replica:
    <<: *default
    database: suite_development
    host: db-replica
    port: 5433
    replica: true
```

Example `app/models/application_record.rb`
```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary, reading: :primary_replica }
end
```

Example `app/models/city.rb`
```ruby
class City < ApplicationRecord
  # code ...
end
```

Example `rails c`
```terminal
irb(main):001:0> ActiveRecord::Base.connected_to(role: :reading) { City.first }
/usr/local/bundle/gems/ros-apartment-3.1.0/lib/apartment/adapters/postgresql_adapter.rb:139:in `raise_schema_connect_to_new': Could not set search path to schemas, they may be invalid: "public" "public". (Apartment::TenantNotFound)
Original error: ActiveRecord::ConnectionNotEstablished: could not connect to server: Connection refused
	Is the server running on host "172.20.0.5" and accepting
	TCP/IP connections on port 5433?

/usr/local/bundle/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client': could not connect to server: Connection refused (ActiveRecord::ConnectionNotEstablished)
	Is the server running on host "172.20.0.5" and accepting
	TCP/IP connections on port 5433?
/usr/local/bundle/gems/pg-1.5.9/lib/pg/connection.rb:709:in `async_connect_or_reset': could not connect to server: Connection refused (PG::ConnectionBad)
	Is the server running on host "172.20.0.5" and accepting
	TCP/IP connections on port 5433?
```

I've tested the configurations above on a AWS environment with success, both primary and primary_replica were running on the same port.

Example `config/database.yml`
```yaml
production:
  primary:
    adapter: "postgresql"
    database: "*****************"
    schema_search_path: "ams"
    encoding: "utf8"
    host: "***************.cluster-***********.us-east-1.rds.amazonaws.com"
    username: "*****************"
    password: "*****************"
    reconnect: true
    port: 5432
  primary_replica:
    adapter: "postgresql"
    database: "*****************"
    schema_search_path: "ams"
    encoding: "utf8"
    host: "***************.cluster-ro-***********.us-east-1.rds.amazonaws.com"
    username: "*****************"
    password: "*****************"
    reconnect: true
    port: 5432
    replica: true
```

Example `rails c`
```terminal
3.0.7 :001 > ActiveRecord::Base.connected_to(role: :reading) { City.first }
  City Load (3.1ms)  SELECT "cities".* FROM "cities" WHERE "cities"."deleted_at" IS NULL ORDER BY "cities"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => 
#<City:0x00005669e9c05e28
 id: 1, ..., deleted_at: nil> 
```

**Expected behavior:** Apartment (and Rails) should connect to `db-replica` on port 5433 when using the `primary_replica` role.

**Actual behavior**: Apartment tries to connect to `db-replica` on port 5432, ignoring the custom port setting, resulting in connection errors if the replica is not exposed on 5432.

**Steps to reproduce:**

- Set up a Rails 6+ app with Apartment and multi-database config as above.
- Expose the replica on a non-default port (e.g., 5433).
- Attempt to use the primary_replica role or connected_to(role: :reading) in code.
- Observe connection errors to the wrong port.

**Environment:**

- Apartment version: 3.1.0 (ros-apartment)
- Rails version: 6.1.3.2
- Ruby: 3.0.7
- PostgreSQL
- Docker Compose
